// @flow
// Web3
export const WEB3_INITIALIZED = 'WEB3_INITIALIZED';
export const WEB3_INITIALIZING = 'WEB3_INITIALIZING';
export const WEB3_INITIALIZATION_ERROR = 'WEB3_INITIALIZATION_ERROR';

// Contract deployment
export const CONTRACT_DEPLOYING = 'CONTRACT_DEPLOYING';
export const CONTRACT_DEPLOYED = 'CONTRACT_DEPLOYED';
export const CONTRACT_DEPLOYMENT_ERROR = 'CONTRACT_DEPLOY_ERROR';

// Trie
export const TRIE_UPDATING = 'TRIE_UPDATING';
export const TRIE_UPDATE = 'TRIE_UPDATE';
export const TRIE_NO_UPDATE = 'TRIE_NO_UPDATE';
export const TRIE_UPDATE_ERROR = 'TRIE_UPDATE_ERROR';

export const TRIE_SET_SELECTED = 'TRIE_SET_SELECTED';
export const TRIE_SET_PREVIOUS_SELECTED = 'TRIE_SET_PREVIOUS_SELECTED';

// Insert
export const INSERT_INSERTING = 'INSERT_INSERTING';
export const INSERT_INSERT_DONE = 'INSERT_INSERT_DONE';
export const INSERT_INSERTION_ERROR = 'INSERT_INSERTION_ERROR';
export const INSERT_KEY = 'INSERT_KEY';
export const INSERT_KEY_ERROR = 'INSERT_KEY_ERROR';
export const INSERT_VALUE = 'INSERT_VALUE';
export const INSERT_VALUE_ERROR = 'INSERT_VALUE_ERROR';

// Get Proof
export const GET_PROOF_GETTING = 'GET_PROOF_GETTING';
export const GET_PROOF_GET = 'GET_PROOF_GET';
export const GET_PROOF_GET_ERROR = 'GET_PROOF_ERROR';
export const GET_PROOF_KEY = 'GET_PROOF_KEY';
export const GET_PROOF_KEY_ERROR = 'GET_PROOF_KEY_ERROR';
export const GET_PROOF_VALUE = 'GET_PROOF_VALUE';


// Keccak256
export const KECCAK_256_GET = 'KECCAK_256_GET';
export const KECCAK_256_INPUT = 'KECCAK_256_INPUT';