// flow-typed signature: 83afaa217ca446aaeb2508078d0f3755
// flow-typed version: <<STUB>>/transfer-webpack-plugin_v^0.1.4/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transfer-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'transfer-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'transfer-webpack-plugin/index' {
  declare module.exports: $Exports<'transfer-webpack-plugin'>;
}
declare module 'transfer-webpack-plugin/index.js' {
  declare module.exports: $Exports<'transfer-webpack-plugin'>;
}
