// flow-typed signature: 3261fc2bbe6988bdb68edba67f18e874
// flow-typed version: <<STUB>>/utf-8_v^1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utf-8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'utf-8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utf-8/karma.conf' {
  declare module.exports: any;
}

declare module 'utf-8/src/UTF8' {
  declare module.exports: any;
}

declare module 'utf-8/tests/main.karma' {
  declare module.exports: any;
}

declare module 'utf-8/tests/utf8.mocha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utf-8/karma.conf.js' {
  declare module.exports: $Exports<'utf-8/karma.conf'>;
}
declare module 'utf-8/src/UTF8.js' {
  declare module.exports: $Exports<'utf-8/src/UTF8'>;
}
declare module 'utf-8/tests/main.karma.js' {
  declare module.exports: $Exports<'utf-8/tests/main.karma'>;
}
declare module 'utf-8/tests/utf8.mocha.js' {
  declare module.exports: $Exports<'utf-8/tests/utf8.mocha'>;
}
